# netlify.toml (place in project root, next to package.json)

[build]
  command = "npm run build"    # or: "ng build --configuration=production"
  publish = "dist/portfolio/browser"   # replace with your Angular output folder

# ✅ SPA routing fix: redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ Optional: Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ✅ Optional: Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"